name: lab7

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        cd lab7
        make test
        ./test
        gcov main.cpp -r
        bash <(curl -s https://codecov.io/bash)

